Added a README.md file
Abhinav-fake/rearrange pull request #1
Opened 2022-10-05 11:36 UTC by Abhinav-ca

adding a README file that was missing for the project

2022-10-05 11:39 UTC, Abhinav-fake requested changes
this is too short. it would be nice to see a example

2022-10-05 12:13 UTC, Abhinav-fake reviewed
make it in one commit

2022-10-07 13:14 UTC, Abhinav-fake requested changes
ok

2022-10-07 13:17 UTC, Abhinav-fake commented on README.md
> +
this line is missing period

2022-10-07 13:20 UTC, Abhinav-fake commented on README.md
> +# Rearrange
it coll but need more examples

2022-10-07 13:22 UTC, Abhinav-fake commented on README.md
> +calling `rearrangename("Turing, Alan")` as a parameter, will return `Alan Turing`
it cool but need more examples

2022-10-07 13:23 UTC, Abhinav-fake commented on README.md
> +# Example
write ## to make it smaller

2022-10-07 13:39 UTC, Abhinav-ca commented
resolved all coment. And please take another look

2023-01-03 08:17 UTC, closed without merging